export interface IngredientInfo {
  ingredient_name: string;
  description: string;
  benefits: string[];
  best_for: string[];
  usage_rate: string;
  category: string;
  ph_notes: string | null;
  cautions: string | null;
}

export const INGREDIENT_DB: Record<string, IngredientInfo> = {
  'shea butter': {
    ingredient_name: 'Shea Butter',
    description: 'A fat extracted from the nut of the African shea tree. Rich in fatty acids and vitamins, it is solid at room temperature and melts on contact with skin.',
    benefits: ['Deep moisturizing', 'Anti-inflammatory', 'Promotes skin elasticity', 'Soothes dry and irritated skin'],
    best_for: ['Dry skin', 'Sensitive skin', 'Eczema-prone skin'],
    usage_rate: '2–30% in lotions, up to 100% as a straight butter',
    category: 'Occlusive / Emollient',
    ph_notes: null,
    cautions: 'May feel heavy in high concentrations for oily skin types.',
  },
  'jojoba oil': {
    ingredient_name: 'Jojoba Oil',
    description: 'A liquid wax extracted from the seed of the jojoba plant. Technically a wax ester, it closely mimics the skin\'s natural sebum and is very stable.',
    benefits: ['Balances oil production', 'Non-comedogenic', 'Long shelf life', 'Lightweight moisturizer'],
    best_for: ['All skin types', 'Acne-prone skin', 'Oily skin'],
    usage_rate: '1–100%',
    category: 'Emollient',
    ph_notes: null,
    cautions: null,
  },
  'niacinamide': {
    ingredient_name: 'Niacinamide (Vitamin B3)',
    description: 'A water-soluble form of vitamin B3. One of the most well-researched skincare actives with a wide range of benefits and excellent tolerability.',
    benefits: ['Reduces pore appearance', 'Controls sebum', 'Brightens skin tone', 'Strengthens skin barrier', 'Reduces redness'],
    best_for: ['Oily skin', 'Acne-prone skin', 'Hyperpigmentation', 'Aging skin'],
    usage_rate: '2–10%',
    category: 'Active',
    ph_notes: 'Stable between pH 5–7. Avoid combining with high-concentration vitamin C as it can cause flushing.',
    cautions: 'At concentrations above 10% may cause flushing in sensitive individuals.',
  },
  'glycerin': {
    ingredient_name: 'Glycerin (Glycerol)',
    description: 'A simple polyol compound that occurs naturally in all living things. One of the most effective and widely used humectants in cosmetics.',
    benefits: ['Draws moisture into skin', 'Improves skin barrier', 'Enhances product spreadability', 'Non-irritating'],
    best_for: ['All skin types', 'Dehydrated skin', 'Sensitive skin'],
    usage_rate: '1–10% in leave-on products',
    category: 'Humectant',
    ph_notes: null,
    cautions: 'At very high concentrations (above 30%) can draw moisture out of skin in low-humidity environments.',
  },
  'hyaluronic acid': {
    ingredient_name: 'Hyaluronic Acid (Sodium Hyaluronate)',
    description: 'A naturally occurring polysaccharide found in connective tissue. Capable of holding up to 1000x its weight in water, making it an exceptional humectant.',
    benefits: ['Intense hydration', 'Plumps fine lines', 'Lightweight feel', 'Compatible with most ingredients'],
    best_for: ['All skin types', 'Dehydrated skin', 'Aging skin'],
    usage_rate: '0.1–2%',
    category: 'Humectant',
    ph_notes: 'Most effective between pH 5–8.',
    cautions: 'Apply to damp skin and seal with an occlusive to prevent moisture loss in dry climates.',
  },
  'btms-50': {
    ingredient_name: 'BTMS-50 (Behentrimonium Methosulfate)',
    description: 'A conditioning emulsifying wax derived from rapeseed oil. Creates rich, creamy emulsions and is a popular choice for hair and skin conditioning products.',
    benefits: ['Effective emulsifier', 'Adds conditioning', 'Creates stable emulsions', 'Imparts silky skin feel'],
    best_for: ['Lotions', 'Creams', 'Hair conditioners'],
    usage_rate: '4–8% as primary emulsifier',
    category: 'Emulsifier',
    ph_notes: null,
    cautions: null,
  },
  'cetyl alcohol': {
    ingredient_name: 'Cetyl Alcohol',
    description: 'A fatty alcohol derived from palm or coconut oil. Despite the name, it is not a drying alcohol — it is a waxy solid that thickens and conditions.',
    benefits: ['Thickens formulas', 'Adds emolliency', 'Improves texture', 'Stabilizes emulsions'],
    best_for: ['Creams', 'Lotions', 'Conditioners'],
    usage_rate: '1–6%',
    category: 'Emollient / Thickener',
    ph_notes: null,
    cautions: null,
  },
  'vitamin e': {
    ingredient_name: 'Vitamin E (Tocopherol)',
    description: 'A fat-soluble antioxidant naturally found in many plant oils. Used in formulations primarily to extend shelf life and provide skin benefits.',
    benefits: ['Antioxidant protection', 'Extends product shelf life', 'Moisturizing', 'Supports skin healing'],
    best_for: ['Dry skin', 'Aging skin', 'Oil-based formulas'],
    usage_rate: '0.5–1%',
    category: 'Antioxidant',
    ph_notes: null,
    cautions: 'Can cause allergic reactions in some individuals at higher concentrations.',
  },
  'aloe vera': {
    ingredient_name: 'Aloe Vera Gel',
    description: 'A gel extracted from the leaves of the aloe plant. Contains polysaccharides, vitamins, and minerals with well-documented soothing properties.',
    benefits: ['Soothes irritated skin', 'Lightweight hydration', 'Anti-inflammatory', 'Cooling effect'],
    best_for: ['Sensitive skin', 'Sunburned skin', 'Oily skin'],
    usage_rate: '2–98%',
    category: 'Humectant / Soothing Agent',
    ph_notes: 'pH around 4.5–5.5.',
    cautions: 'Some people have aloe allergies — patch test recommended.',
  },
  'sodium percarbonate': {
    ingredient_name: 'Sodium Percarbonate',
    description: 'An oxidizing agent that releases hydrogen peroxide when dissolved in water. Used as an oxygen bleach in laundry and cleaning formulations.',
    benefits: ['Effective stain removal', 'Brightens whites', 'Kills bacteria and mold', 'Breaks down to water and soda ash'],
    best_for: ['Laundry powder', 'Cleaning products', 'Whitening formulas'],
    usage_rate: '10–30% in laundry powder',
    category: 'Oxidizing Agent / Bleach',
    ph_notes: 'Creates alkaline solution when dissolved.',
    cautions: 'Keep dry — moisture activates it. Not for use on wool or silk. Irritating to eyes.',
  },
  'washing soda': {
    ingredient_name: 'Washing Soda (Sodium Carbonate)',
    description: 'A highly alkaline salt used as a water softener and cleaning booster. Also known as soda ash, it is a key ingredient in DIY laundry formulas.',
    benefits: ['Softens hard water', 'Boosts cleaning power', 'Removes grease and stains', 'Inexpensive'],
    best_for: ['Laundry powder', 'Cleaning products'],
    usage_rate: '30–50% in laundry powder',
    category: 'Alkaline Builder',
    ph_notes: 'Highly alkaline — pH around 11.',
    cautions: 'Irritating to skin and eyes. Not for delicate fabrics. Do not confuse with baking soda.',
  },
  'slsa': {
    ingredient_name: 'SLSA (Sodium Lauryl Sulfoacetate)',
    description: 'A mild, plant-derived surfactant that creates a fluffy lather. Often confused with SLS but much gentler and derived from coconut and palm oils.',
    benefits: ['Gentle cleansing', 'Rich fluffy lather', 'Less irritating than SLS', 'Safe for sensitive skin'],
    best_for: ['Bath bombs', 'Bubble bath', 'Gentle cleansers', 'Laundry powder'],
    usage_rate: '5–25%',
    category: 'Surfactant',
    ph_notes: null,
    cautions: 'Fine powder — use a mask when handling to avoid inhaling.',
  },
  'coconut oil': {
    ingredient_name: 'Coconut Oil',
    description: 'A saturated fat extracted from fresh coconut meat. High in lauric acid, it is solid at room temperature and has antimicrobial properties.',
    benefits: ['Moisturizing', 'Antimicrobial', 'Creates hard bar soap', 'Good lather in soap making'],
    best_for: ['Soap making', 'Hair care', 'Body products'],
    usage_rate: '15–30% in soap, 1–10% in skin products',
    category: 'Occlusive / Emollient',
    ph_notes: null,
    cautions: 'Comedogenic rating of 4 — can clog pores for acne-prone skin in leave-on products. Fractionated coconut oil is lighter and non-comedogenic.',
  },
  'castile soap': {
    ingredient_name: 'Castile Soap',
    description: 'A vegetable-based soap traditionally made with olive oil, now referring broadly to any plant-oil-based liquid or bar soap without synthetic detergents.',
    benefits: ['Gentle cleansing', 'Biodegradable', 'Versatile', 'Free of synthetic detergents'],
    best_for: ['Sensitive skin', 'Natural cleaning', 'DIY household products'],
    usage_rate: 'As needed — used as a base',
    category: 'Surfactant / Cleanser',
    ph_notes: 'Highly alkaline — pH 9–11. Do not mix with acidic ingredients like vinegar.',
    cautions: 'Mixing with acids (vinegar, citric acid) will unsaponify the soap and cause curdling.',
  },
  'sunflower oil': {
    ingredient_name: 'Sunflower Seed Oil',
    description: 'A light, non-greasy oil high in linoleic acid extracted from sunflower seeds. One of the best oils for sensitive and acne-prone skin.',
    benefits: ['High linoleic acid content', 'Lightweight', 'Supports skin barrier', 'Non-comedogenic'],
    best_for: ['Sensitive skin', 'Acne-prone skin', 'Dry skin'],
    usage_rate: '1–100%',
    category: 'Emollient',
    ph_notes: null,
    cautions: 'Shorter shelf life than some oils — add vitamin E to extend.',
  },
  'beeswax': {
    ingredient_name: 'Beeswax',
    description: 'A natural wax produced by honeybees. Used in cosmetics to thicken, provide structure, and create a protective barrier on the skin.',
    benefits: ['Thickens and hardens formulas', 'Creates protective barrier', 'Locks in moisture', 'Natural preservative properties'],
    best_for: ['Lip balm', 'Body butter', 'Salves', 'Lotion bars'],
    usage_rate: '5–30% depending on desired hardness',
    category: 'Wax / Thickener',
    ph_notes: null,
    cautions: 'Not vegan. Can feel heavy on skin at high concentrations.',
  },
  'colloidal oatmeal': {
    ingredient_name: 'Colloidal Oatmeal',
    description: 'Finely milled oats processed to disperse in water. FDA-approved as a skin protectant with well-documented anti-itch and soothing properties.',
    benefits: ['Soothes itch and irritation', 'Anti-inflammatory', 'Gentle exfoliation', 'Strengthens skin barrier'],
    best_for: ['Eczema', 'Sensitive skin', 'Dry itchy skin'],
    usage_rate: '0.5–5%',
    category: 'Soothing Agent / Skin Protectant',
    ph_notes: null,
    cautions: 'Must be finely milled to disperse properly. Avoid in formulas if oat allergy is a concern.',
  },
  'panthenol': {
    ingredient_name: 'Panthenol (Pro-Vitamin B5)',
    description: 'The alcohol form of pantothenic acid (vitamin B5). Converts to vitamin B5 in the skin and is prized for its moisturizing and healing properties.',
    benefits: ['Deep moisturizing', 'Promotes wound healing', 'Reduces inflammation', 'Improves skin elasticity'],
    best_for: ['Dry skin', 'Damaged skin', 'Hair care'],
    usage_rate: '0.5–5%',
    category: 'Humectant / Skin Conditioning Agent',
    ph_notes: 'Stable between pH 4–7.',
    cautions: null,
  },
  'allantoin': {
    ingredient_name: 'Allantoin',
    description: 'A naturally occurring compound found in comfrey root. Known for its ability to soothe skin and accelerate cell regeneration.',
    benefits: ['Soothes and calms skin', 'Promotes cell turnover', 'Anti-irritant', 'Softens keratin'],
    best_for: ['Sensitive skin', 'Acne-prone skin', 'After-sun care'],
    usage_rate: '0.1–2%',
    category: 'Soothing Agent',
    ph_notes: 'Dissolves better in warm water. Add to water phase when heated.',
    cautions: null,
  },
  'citric acid': {
    ingredient_name: 'Citric Acid',
    description: 'A weak organic acid found naturally in citrus fruits. Used in cosmetics primarily to adjust pH and as a preservative booster.',
    benefits: ['pH adjustment', 'Preservative booster', 'Mild AHA exfoliant at higher concentrations', 'Chelating agent'],
    best_for: ['pH adjustment in all formulas', 'Bath bombs (reacts with baking soda)', 'Toners'],
    usage_rate: 'As needed for pH adjustment, 1–10% as active',
    category: 'pH Adjuster / AHA',
    ph_notes: 'Very acidic — use in small amounts to lower pH. Key ingredient in bath bomb fizz reaction.',
    cautions: 'Do not mix directly with castile soap or other alkaline ingredients without diluting first.',
  },
};


const INGREDIENT_DB: Record<string, IngredientInfo> = {
  'shea butter': {
    ingredient_name: 'Shea Butter',
    description: 'A fat extracted from the nut of the African shea tree. Rich in fatty acids and vitamins, it is solid at room temperature and melts on contact with skin.',
    benefits: ['Deep moisturizing', 'Anti-inflammatory', 'Promotes skin elasticity', 'Soothes dry and irritated skin'],
    best_for: ['Dry skin', 'Sensitive skin', 'Eczema-prone skin'],
    usage_rate: '2–30% in lotions, up to 100% as a straight butter',
    category: 'Occlusive / Emollient',
    ph_notes: null,
    cautions: 'May feel heavy in high concentrations for oily skin types.',
  },
  'jojoba oil': {
    ingredient_name: 'Jojoba Oil',
    description: 'A liquid wax extracted from the seed of the jojoba plant. Technically a wax ester, it closely mimics the skin\'s natural sebum and is very stable.',
    benefits: ['Balances oil production', 'Non-comedogenic', 'Long shelf life', 'Lightweight moisturizer'],
    best_for: ['All skin types', 'Acne-prone skin', 'Oily skin'],
    usage_rate: '1–100%',
    category: 'Emollient',
    ph_notes: null,
    cautions: null,
  },
  'niacinamide': {
    ingredient_name: 'Niacinamide (Vitamin B3)',
    description: 'A water-soluble form of vitamin B3. One of the most well-researched skincare actives with a wide range of benefits and excellent tolerability.',
    benefits: ['Reduces pore appearance', 'Controls sebum', 'Brightens skin tone', 'Strengthens skin barrier', 'Reduces redness'],
    best_for: ['Oily skin', 'Acne-prone skin', 'Hyperpigmentation', 'Aging skin'],
    usage_rate: '2–10%',
    category: 'Active',
    ph_notes: 'Stable between pH 5–7. Avoid combining with high-concentration vitamin C as it can cause flushing.',
    cautions: 'At concentrations above 10% may cause flushing in sensitive individuals.',
  },
  'glycerin': {
    ingredient_name: 'Glycerin (Glycerol)',
    description: 'A simple polyol compound that occurs naturally in all living things. One of the most effective and widely used humectants in cosmetics.',
    benefits: ['Draws moisture into skin', 'Improves skin barrier', 'Enhances product spreadability', 'Non-irritating'],
    best_for: ['All skin types', 'Dehydrated skin', 'Sensitive skin'],
    usage_rate: '1–10% in leave-on products',
    category: 'Humectant',
    ph_notes: null,
    cautions: 'At very high concentrations (above 30%) can draw moisture out of skin in low-humidity environments.',
  },
  'hyaluronic acid': {
    ingredient_name: 'Hyaluronic Acid (Sodium Hyaluronate)',
    description: 'A naturally occurring polysaccharide found in connective tissue. Capable of holding up to 1000x its weight in water, making it an exceptional humectant.',
    benefits: ['Intense hydration', 'Plumps fine lines', 'Lightweight feel', 'Compatible with most ingredients'],
    best_for: ['All skin types', 'Dehydrated skin', 'Aging skin'],
    usage_rate: '0.1–2%',
    category: 'Humectant',
    ph_notes: 'Most effective between pH 5–8.',
    cautions: 'Apply to damp skin and seal with an occlusive to prevent moisture loss in dry climates.',
  },
  'btms-50': {
    ingredient_name: 'BTMS-50 (Behentrimonium Methosulfate)',
    description: 'A conditioning emulsifying wax derived from rapeseed oil. Creates rich, creamy emulsions and is a popular choice for hair and skin conditioning products.',
    benefits: ['Effective emulsifier', 'Adds conditioning', 'Creates stable emulsions', 'Imparts silky skin feel'],
    best_for: ['Lotions', 'Creams', 'Hair conditioners'],
    usage_rate: '4–8% as primary emulsifier',
    category: 'Emulsifier',
    ph_notes: null,
    cautions: null,
  },
  'cetyl alcohol': {
    ingredient_name: 'Cetyl Alcohol',
    description: 'A fatty alcohol derived from palm or coconut oil. Despite the name, it is not a drying alcohol — it is a waxy solid that thickens and conditions.',
    benefits: ['Thickens formulas', 'Adds emolliency', 'Improves texture', 'Stabilizes emulsions'],
    best_for: ['Creams', 'Lotions', 'Conditioners'],
    usage_rate: '1–6%',
    category: 'Emollient / Thickener',
    ph_notes: null,
    cautions: null,
  },
  'vitamin e': {
    ingredient_name: 'Vitamin E (Tocopherol)',
    description: 'A fat-soluble antioxidant naturally found in many plant oils. Used in formulations primarily to extend shelf life and provide skin benefits.',
    benefits: ['Antioxidant protection', 'Extends product shelf life', 'Moisturizing', 'Supports skin healing'],
    best_for: ['Dry skin', 'Aging skin', 'Oil-based formulas'],
    usage_rate: '0.5–1%',
    category: 'Antioxidant',
    ph_notes: null,
    cautions: 'Can cause allergic reactions in some individuals at higher concentrations.',
  },
  'aloe vera': {
    ingredient_name: 'Aloe Vera Gel',
    description: 'A gel extracted from the leaves of the aloe plant. Contains polysaccharides, vitamins, and minerals with well-documented soothing properties.',
    benefits: ['Soothes irritated skin', 'Lightweight hydration', 'Anti-inflammatory', 'Cooling effect'],
    best_for: ['Sensitive skin', 'Sunburned skin', 'Oily skin'],
    usage_rate: '2–98%',
    category: 'Humectant / Soothing Agent',
    ph_notes: 'pH around 4.5–5.5.',
    cautions: 'Some people have aloe allergies — patch test recommended.',
  },
  'sodium percarbonate': {
    ingredient_name: 'Sodium Percarbonate',
    description: 'An oxidizing agent that releases hydrogen peroxide when dissolved in water. Used as an oxygen bleach in laundry and cleaning formulations.',
    benefits: ['Effective stain removal', 'Brightens whites', 'Kills bacteria and mold', 'Breaks down to water and soda ash'],
    best_for: ['Laundry powder', 'Cleaning products', 'Whitening formulas'],
    usage_rate: '10–30% in laundry powder',
    category: 'Oxidizing Agent / Bleach',
    ph_notes: 'Creates alkaline solution when dissolved.',
    cautions: 'Keep dry — moisture activates it. Not for use on wool or silk. Irritating to eyes.',
  },
  'washing soda': {
    ingredient_name: 'Washing Soda (Sodium Carbonate)',
    description: 'A highly alkaline salt used as a water softener and cleaning booster. Also known as soda ash, it is a key ingredient in DIY laundry formulas.',
    benefits: ['Softens hard water', 'Boosts cleaning power', 'Removes grease and stains', 'Inexpensive'],
    best_for: ['Laundry powder', 'Cleaning products'],
    usage_rate: '30–50% in laundry powder',
    category: 'Alkaline Builder',
    ph_notes: 'Highly alkaline — pH around 11.',
    cautions: 'Irritating to skin and eyes. Not for delicate fabrics. Do not confuse with baking soda.',
  },
  'slsa': {
    ingredient_name: 'SLSA (Sodium Lauryl Sulfoacetate)',
    description: 'A mild, plant-derived surfactant that creates a fluffy lather. Often confused with SLS but much gentler and derived from coconut and palm oils.',
    benefits: ['Gentle cleansing', 'Rich fluffy lather', 'Less irritating than SLS', 'Safe for sensitive skin'],
    best_for: ['Bath bombs', 'Bubble bath', 'Gentle cleansers', 'Laundry powder'],
    usage_rate: '5–25%',
    category: 'Surfactant',
    ph_notes: null,
    cautions: 'Fine powder — use a mask when handling to avoid inhaling.',
  },
  'coconut oil': {
    ingredient_name: 'Coconut Oil',
    description: 'A saturated fat extracted from fresh coconut meat. High in lauric acid, it is solid at room temperature and has antimicrobial properties.',
    benefits: ['Moisturizing', 'Antimicrobial', 'Creates hard bar soap', 'Good lather in soap making'],
    best_for: ['Soap making', 'Hair care', 'Body products'],
    usage_rate: '15–30% in soap, 1–10% in skin products',
    category: 'Occlusive / Emollient',
    ph_notes: null,
    cautions: 'Comedogenic rating of 4 — can clog pores for acne-prone skin in leave-on products. Fractionated coconut oil is lighter and non-comedogenic.',
  },
  'castile soap': {
    ingredient_name: 'Castile Soap',
    description: 'A vegetable-based soap traditionally made with olive oil, now referring broadly to any plant-oil-based liquid or bar soap without synthetic detergents.',
    benefits: ['Gentle cleansing', 'Biodegradable', 'Versatile', 'Free of synthetic detergents'],
    best_for: ['Sensitive skin', 'Natural cleaning', 'DIY household products'],
    usage_rate: 'As needed — used as a base',
    category: 'Surfactant / Cleanser',
    ph_notes: 'Highly alkaline — pH 9–11. Do not mix with acidic ingredients like vinegar.',
    cautions: 'Mixing with acids (vinegar, citric acid) will unsaponify the soap and cause curdling.',
  },
  'sunflower oil': {
    ingredient_name: 'Sunflower Seed Oil',
    description: 'A light, non-greasy oil high in linoleic acid extracted from sunflower seeds. One of the best oils for sensitive and acne-prone skin.',
    benefits: ['High linoleic acid content', 'Lightweight', 'Supports skin barrier', 'Non-comedogenic'],
    best_for: ['Sensitive skin', 'Acne-prone skin', 'Dry skin'],
    usage_rate: '1–100%',
    category: 'Emollient',
    ph_notes: null,
    cautions: 'Shorter shelf life than some oils — add vitamin E to extend.',
  },
  'beeswax': {
    ingredient_name: 'Beeswax',
    description: 'A natural wax produced by honeybees. Used in cosmetics to thicken, provide structure, and create a protective barrier on the skin.',
    benefits: ['Thickens and hardens formulas', 'Creates protective barrier', 'Locks in moisture', 'Natural preservative properties'],
    best_for: ['Lip balm', 'Body butter', 'Salves', 'Lotion bars'],
    usage_rate: '5–30% depending on desired hardness',
    category: 'Wax / Thickener',
    ph_notes: null,
    cautions: 'Not vegan. Can feel heavy on skin at high concentrations.',
  },
  'colloidal oatmeal': {
    ingredient_name: 'Colloidal Oatmeal',
    description: 'Finely milled oats processed to disperse in water. FDA-approved as a skin protectant with well-documented anti-itch and soothing properties.',
    benefits: ['Soothes itch and irritation', 'Anti-inflammatory', 'Gentle exfoliation', 'Strengthens skin barrier'],
    best_for: ['Eczema', 'Sensitive skin', 'Dry itchy skin'],
    usage_rate: '0.5–5%',
    category: 'Soothing Agent / Skin Protectant',
    ph_notes: null,
    cautions: 'Must be finely milled to disperse properly. Avoid in formulas if oat allergy is a concern.',
  },
  'panthenol': {
    ingredient_name: 'Panthenol (Pro-Vitamin B5)',
    description: 'The alcohol form of pantothenic acid (vitamin B5). Converts to vitamin B5 in the skin and is prized for its moisturizing and healing properties.',
    benefits: ['Deep moisturizing', 'Promotes wound healing', 'Reduces inflammation', 'Improves skin elasticity'],
    best_for: ['Dry skin', 'Damaged skin', 'Hair care'],
    usage_rate: '0.5–5%',
    category: 'Humectant / Skin Conditioning Agent',
    ph_notes: 'Stable between pH 4–7.',
    cautions: null,
  },
  'allantoin': {
    ingredient_name: 'Allantoin',
    description: 'A naturally occurring compound found in comfrey root. Known for its ability to soothe skin and accelerate cell regeneration.',
    benefits: ['Soothes and calms skin', 'Promotes cell turnover', 'Anti-irritant', 'Softens keratin'],
    best_for: ['Sensitive skin', 'Acne-prone skin', 'After-sun care'],
    usage_rate: '0.1–2%',
    category: 'Soothing Agent',
    ph_notes: 'Dissolves better in warm water. Add to water phase when heated.',
    cautions: null,
  },
  'citric acid': {
    ingredient_name: 'Citric Acid',
    description: 'A weak organic acid found naturally in citrus fruits. Used in cosmetics primarily to adjust pH and as a preservative booster.',
    benefits: ['pH adjustment', 'Preservative booster', 'Mild AHA exfoliant at higher concentrations', 'Chelating agent'],
    best_for: ['pH adjustment in all formulas', 'Bath bombs (reacts with baking soda)', 'Toners'],
    usage_rate: 'As needed for pH adjustment, 1–10% as active',
    category: 'pH Adjuster / AHA',
    ph_notes: 'Very acidic — use in small amounts to lower pH. Key ingredient in bath bomb fizz reaction.',
    cautions: 'Do not mix directly with castile soap or other alkaline ingredients without diluting first.',
  },
};
